/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package thebordacount;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;


/**
 *
 * @author Alleb_D
 */
public class Candidates extends javax.swing.JFrame {
    int candidate1 = 0;
    int candidate2 = 0;
    int candidate3 = 0;
    int candidate4 = 0;
    int candidate5 = 0;
    int candidate6 = 0;
    int peterid, peterscore, paulid, paulscore, ruthid, ruthscore, annid, annscore, amosid, amosscore, giftid, giftscore;
    /**
     * Creates new form Login
     */
    public Candidates() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    
    
    
    
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btn_submit = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txt_candidate1 = new javax.swing.JTextField();
        txt_candidate2 = new javax.swing.JTextField();
        txt_candidate3 = new javax.swing.JTextField();
        txt_candidate4 = new javax.swing.JTextField();
        txt_candidate5 = new javax.swing.JTextField();
        txt_candidate6 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btn_submit.setText("Vote");
        btn_submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_submitActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/thebordacount/chiara_50x50.jpg"))); // NOI18N

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/thebordacount/afro_50x50.jpg"))); // NOI18N

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/thebordacount/amaze_50x50.jpg"))); // NOI18N

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/thebordacount/gamer_chick_50x50.jpg"))); // NOI18N

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/thebordacount/me_with_the_uke_50x50.jpg"))); // NOI18N

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/thebordacount/bubbles_50x50.jpg"))); // NOI18N

        jLabel8.setText("Peter");

        jLabel9.setText("Paul");

        jLabel10.setText("Ruth");

        jLabel11.setText("Ann");

        jLabel12.setText("Gift");

        jLabel13.setText("Amos");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setText("Pick the number 1-6 for each candidates according to your scale of preference, do not repeat each number, number 1 to signify the best.");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel6))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel8)
                                    .addComponent(txt_candidate1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(70, 70, 70)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9)
                                    .addComponent(txt_candidate2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(61, 61, 61)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txt_candidate3, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel10))))
                        .addGap(103, 103, 103)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel11)
                                    .addComponent(txt_candidate4, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(87, 87, 87)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txt_candidate5, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel12))))
                        .addGap(39, 39, 39)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txt_candidate6, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel13))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(334, 334, 334)
                .addComponent(btn_submit)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12)
                    .addComponent(jLabel13))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_candidate1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_candidate2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_candidate3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_candidate4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_candidate5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_candidate6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addComponent(btn_submit)
                .addGap(35, 35, 35))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_submitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_submitActionPerformed
        // TODO add your handling code here:
        try{
            candidate1 = Integer.parseInt(txt_candidate1.getText().trim());
            candidate2 = Integer.parseInt(txt_candidate2.getText().trim());
            candidate3 = Integer.parseInt(txt_candidate3.getText().trim());
            candidate4 = Integer.parseInt(txt_candidate4.getText().trim());
            candidate5 = Integer.parseInt(txt_candidate5.getText().trim());
            candidate6 = Integer.parseInt(txt_candidate6.getText().trim());
            // is an integer!
            
            if(candidate1 == candidate2 || candidate1 == candidate3 || candidate1 == candidate4 || candidate1 == candidate5 || candidate1 == candidate6
                || candidate2 == candidate3 || candidate2 == candidate4 || candidate2 == candidate5 || candidate2 == candidate6 
                || candidate3 == candidate4 || candidate3 == candidate5 || candidate3 == candidate6 
                || candidate4 == candidate5 || candidate4 == candidate6 
                || candidate5 == candidate6){
                JOptionPane.showMessageDialog(null, "You have inputted the same number twice");
            }else{
                Connection connection;
                PreparedStatement pt,pl,rt,an,gf,am;
                try {            
                    try {
                        Class.forName("com.mysql.jdbc.Driver");
                        System.out.println("Driver loaded!");
                    } catch (ClassNotFoundException e) {
                        throw new IllegalStateException("Cannot find the driver in the classpath!", e);
                    }
                    connection = DriverManager.getConnection("jdbc:mysql://localhost:3306/bordacount", "root", "IBUKUN");
                    pt = connection.prepareStatement("SELECT * FROM `candidates` WHERE `candidate_name` = 'Peter'");
                    ResultSet result = pt.executeQuery();
                    while(result.next()){
                        peterid = result.getInt("candidate_id");
                        peterscore = result.getInt("candidate_score");
                    }

                    pl = connection.prepareStatement("SELECT * FROM `candidates` WHERE `candidate_name` = 'Paul'");
                    ResultSet plresult = pl.executeQuery();
                    while(plresult.next()){
                        paulid = plresult.getInt("candidate_id");
                        paulscore = plresult.getInt("candidate_score");
                    }

                    rt = connection.prepareStatement("SELECT * FROM `candidates` WHERE `candidate_name` = 'Ruth'");
                    ResultSet rtresult = rt.executeQuery();
                    while(rtresult.next()){
                        ruthid = rtresult.getInt("candidate_id");
                        ruthscore = rtresult.getInt("candidate_score");
                    }

                    an = connection.prepareStatement("SELECT * FROM `candidates` WHERE `candidate_name` = 'Ann'");
                    ResultSet anresult = an.executeQuery();
                    while(anresult.next()){
                        annid = anresult.getInt("candidate_id");
                        annscore = anresult.getInt("candidate_score");
                    }

                    am = connection.prepareStatement("SELECT * FROM `candidates` WHERE `candidate_name` = 'Amos'");
                    ResultSet amresult = am.executeQuery();
                    while(amresult.next()){
                        amosid = amresult.getInt("candidate_id");
                        amosscore = amresult.getInt("candidate_score");
                    }

                    gf = connection.prepareStatement("SELECT * FROM `candidates` WHERE `candidate_name` = 'Gift'");
                    ResultSet gfresult = gf.executeQuery();
                    while(gfresult.next()){
                        giftid = gfresult.getInt("candidate_id");
                        giftscore = gfresult.getInt("candidate_score");
                    }
                } catch (SQLException ex) {
                    Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
                }

                int n = 7;
                int cand1, cand2, cand3, cand4, cand5, cand6;
                int cand1new, cand2new, cand3new, cand4new, cand5new, cand6new;
                if(candidate1 == 1)
                {
                    cand1 = n - 1;                
                }else if(candidate1 == 2)
                {
                    cand1 = n - 2;
                }else if(candidate1 == 3)
                {
                    cand1 = n - 3;
                }else if(candidate1 == 4)
                {
                    cand1 = n - 4;
                }else if(candidate1 == 5)
                {
                    cand1 = n - 5;
                }else if(candidate1 == 6)
                {
                    cand1 = n - 6;
                }else{
                    cand1 = 0;
                }

                if(candidate2 == 1)
                {
                    cand2 = n - 1;
                }else if(candidate2 == 2)
                {
                    cand2 = n - 2;
                }else if(candidate2 == 3)
                {
                    cand2 = n - 3;
                }else if(candidate2 == 4)
                {
                    cand2 = n - 4;
                }else if(candidate2 == 5)
                {
                    cand2 = n - 5;
                }else if(candidate2 == 6)
                {
                    cand2 = n - 6;
                }else{
                    cand2 = 0;
                }

                if(candidate3 == 1)
                {
                    cand3 = n - 1;
                }else if(candidate3 == 2)
                {
                    cand3 = n - 2;
                }else if(candidate3 == 3)
                {
                    cand3 = n - 3;
                }else if(candidate3 == 4)
                {
                    cand3 = n - 4;
                }else if(candidate3 == 5)
                {
                    cand3 = n - 5;
                }else if(candidate3 == 6)
                {
                    cand3 = n - 6;
                }else{
                    cand3 = 0;
                }

                if(candidate4 == 1)
                {
                    cand4 = n - 1;
                }else if(candidate4 == 2)
                {
                    cand4 = n - 2;
                }else if(candidate4 == 3)
                {
                    cand4 = n - 3;
                }else if(candidate4 == 4)
                {
                    cand4 = n - 4;
                }else if(candidate4 == 5)
                {
                    cand4 = n - 5;
                }else if(candidate4 == 6)
                {
                    cand4 = n - 6;
                }else{
                    cand4 = 0;
                }

                if(candidate5 == 1)
                {
                    cand5 = n - 1;
                }else if(candidate5 == 2)
                {
                    cand5 = n - 2;
                }else if(candidate5 == 3)
                {
                    cand5 = n - 3;
                }else if(candidate5 == 4)
                {
                    cand5 = n - 4;
                }else if(candidate5 == 5)
                {
                    cand5 = n - 5;
                }else if(candidate5 == 6)
                {
                    cand5 = n - 6;
                }else{
                    cand5 = 0;
                }

                if(candidate6 == 1)
                {
                    cand6 = n - 1;
                }else if(candidate6 == 2)
                {
                    cand6 = n - 2;
                }else if(candidate6 == 3)
                {
                    cand6 = n - 3;
                }else if(candidate6 == 4)
                {
                    cand6 = n - 4;
                }else if(candidate6 == 5)
                {
                    cand6 = n - 5;
                }else if(candidate6 == 6)
                {
                    cand6 = n - 6;
                }else{
                    cand6 = 0;
                }

                cand1new = cand1 + peterscore;
                cand2new = cand2 + paulscore;
                cand3new = cand3 + ruthscore;
                cand4new = cand4 + annscore;
                cand5new = cand5 + giftscore;
                cand6new = cand6 + amosscore;

                Connection conn;
                PreparedStatement ptup,plup,rtup,anup,gfup,amup;
                try {            
                    try {
                        Class.forName("com.mysql.jdbc.Driver");
                        System.out.println("Driver loaded!");
                    } catch (ClassNotFoundException e) {
                        throw new IllegalStateException("Cannot find the driver in the classpath!", e);
                    }
                    conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/bordacount", "root", "IBUKUN");
                    ptup = conn.prepareStatement("UPDATE `candidates` SET `candidate_score`= ? WHERE `candidate_id`= ?");
                    ptup.setInt(1, cand1new);
                    ptup.setInt(2, peterid);
                    ptup.executeUpdate();

                    plup = conn.prepareStatement("UPDATE `candidates` SET `candidate_score`= ? WHERE `candidate_id`= ?");
                    plup.setInt(1, cand2new);
                    plup.setInt(2, paulid);
                    plup.executeUpdate();

                    rtup = conn.prepareStatement("UPDATE `candidates` SET `candidate_score`= ? WHERE `candidate_id`= ?");
                    rtup.setInt(1, cand3new);
                    rtup.setInt(2, ruthid);
                    rtup.executeUpdate();

                    anup = conn.prepareStatement("UPDATE `candidates` SET `candidate_score`= ? WHERE `candidate_id`= ?");
                    anup.setInt(1, cand4new);
                    anup.setInt(2, annid);
                    anup.executeUpdate();

                    gfup = conn.prepareStatement("UPDATE `candidates` SET `candidate_score`= ? WHERE `candidate_id`= ?");
                    gfup.setInt(1, cand5new);
                    gfup.setInt(2, giftid);
                    gfup.executeUpdate();

                    amup = conn.prepareStatement("UPDATE `candidates` SET `candidate_score`= ? WHERE `candidate_id`= ?");
                    amup.setInt(1, cand6new);
                    amup.setInt(2, amosid);
                    amup.executeUpdate();

                    dispose();
                    Winner thewinner = new Winner();
                    thewinner.setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
            } catch (NumberFormatException e) {
            // not an integer!
            JOptionPane.showMessageDialog(null, "You have not entered a number in all fields");
          }              
        
    }//GEN-LAST:event_btn_submitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Candidates.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Candidates.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Candidates.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Candidates.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Candidates().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_submit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txt_candidate1;
    private javax.swing.JTextField txt_candidate2;
    private javax.swing.JTextField txt_candidate3;
    private javax.swing.JTextField txt_candidate4;
    private javax.swing.JTextField txt_candidate5;
    private javax.swing.JTextField txt_candidate6;
    // End of variables declaration//GEN-END:variables
}
