/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package thebordacount;

import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Timer;

/**
 *
 * @author Alleb_D
 */
public class Registration extends javax.swing.JFrame {
    
    /**
     * Creates new form Login
     */
    public Registration() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    Timer timer1 = new Timer(30, new ActionListener() {

        @Override
        public void actionPerformed(ActionEvent e) {
            
            if(messagebox.getHeight() != 78){
                messagebox.setBounds(0,0,Registration.this.getSize().width,messagebox.getHeight() + 3);
                if(messagebox.getHeight() == 78){
                    timer1.stop();
                }
            }
        }
    });
    
    Timer timer2 = new Timer(30, new ActionListener() {

        @Override
        public void actionPerformed(ActionEvent e) {
            
            if(messagebox.getHeight() != 0){
                messagebox.setBounds(0,0,Registration.this.getSize().width,messagebox.getHeight() - 3);
                if(messagebox.getHeight() == 0){
                    timer2.stop();
                }
            }
        }
    });
    
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lbl_username = new javax.swing.JLabel();
        lbl_password = new javax.swing.JLabel();
        txt_first = new javax.swing.JTextField();
        txt_cpassword = new javax.swing.JPasswordField();
        btn_register = new javax.swing.JButton();
        messagebox = new javax.swing.JPanel();
        themessage = new javax.swing.JLabel();
        ok = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        loginnow = new javax.swing.JButton();
        lbl_username1 = new javax.swing.JLabel();
        txt_last = new javax.swing.JTextField();
        lbl_username2 = new javax.swing.JLabel();
        txt_age = new javax.swing.JTextField();
        lbl_username3 = new javax.swing.JLabel();
        txt_occupation = new javax.swing.JTextField();
        lbl_username4 = new javax.swing.JLabel();
        txt_gender = new javax.swing.JTextField();
        lbl_username6 = new javax.swing.JLabel();
        txt_email = new javax.swing.JTextField();
        lbl_username7 = new javax.swing.JLabel();
        txt_nim = new javax.swing.JTextField();
        lbl_password1 = new javax.swing.JLabel();
        txt_password = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setName("frame"); // NOI18N

        lbl_username.setText("First Name");

        lbl_password.setText("Confirm Password");

        txt_first.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_firstActionPerformed(evt);
            }
        });

        btn_register.setText("Register");
        btn_register.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_registerActionPerformed(evt);
            }
        });

        messagebox.setBackground(java.awt.Color.decode("#3a5795")
        );
        messagebox.setPreferredSize(new java.awt.Dimension(441, 78));

        themessage.setForeground(new java.awt.Color(255, 255, 255));

        ok.setText("OK");
        ok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout messageboxLayout = new javax.swing.GroupLayout(messagebox);
        messagebox.setLayout(messageboxLayout);
        messageboxLayout.setHorizontalGroup(
            messageboxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(messageboxLayout.createSequentialGroup()
                .addContainerGap(28, Short.MAX_VALUE)
                .addComponent(themessage, javax.swing.GroupLayout.PREFERRED_SIZE, 341, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(ok)
                .addGap(56, 56, 56))
        );
        messageboxLayout.setVerticalGroup(
            messageboxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(messageboxLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(messageboxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(ok, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(themessage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("Register to Vote");

        loginnow.setText("Log In ");
        loginnow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginnowActionPerformed(evt);
            }
        });

        lbl_username1.setText("Last Name");

        lbl_username2.setText("Occupation");

        lbl_username3.setText("Age");

        lbl_username4.setText("Gender");

        lbl_username6.setText("Email");

        lbl_username7.setText("NIM");

        lbl_password1.setText("Password");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(messagebox, javax.swing.GroupLayout.DEFAULT_SIZE, 490, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(183, 183, 183)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(39, 39, 39)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lbl_username6, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(lbl_password1))
                                        .addComponent(lbl_username7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addComponent(lbl_password))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txt_cpassword, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btn_register)
                                .addComponent(loginnow)
                                .addComponent(txt_email, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txt_nim, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txt_password, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(125, 125, 125)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lbl_username2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(lbl_username1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addGap(1, 1, 1)
                                            .addComponent(lbl_username, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(lbl_username3)))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                    .addContainerGap()
                                    .addComponent(lbl_username4, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(txt_gender, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                                .addComponent(txt_occupation, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txt_age, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txt_last, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txt_first, javax.swing.GroupLayout.Alignment.LEADING)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(messagebox, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(139, 139, 139)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_username)
                    .addComponent(txt_first, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_username1)
                    .addComponent(txt_last, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_age, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_username3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_occupation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_username2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_gender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_username4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbl_username6)
                    .addComponent(txt_email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_nim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_username7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_password1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_password)
                    .addComponent(txt_cpassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addComponent(btn_register)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(loginnow)
                .addGap(57, 57, 57))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_registerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_registerActionPerformed
        // TODO add your handling code here:
        Connection connection;
        PreparedStatement ps;
        String vin="";
        try {            
            try {
                Class.forName("com.mysql.jdbc.Driver");
                System.out.println("Driver loaded!");
            } catch (ClassNotFoundException e) {
                throw new IllegalStateException("Cannot find the driver in the classpath!", e);
            }
            connection = DriverManager.getConnection("jdbc:mysql://localhost:3306/bordacount", "root", "IBUKUN");
            ps = connection.prepareStatement("SELECT * FROM `users` ORDER BY user_id DESC LIMIT 1");
            ResultSet result = ps.executeQuery();
            if(result.next()){
                vin = "vin0"+result.getInt("user_id");
            }else{
                vin = "vin00";
            }
        } catch (SQLException ex) {
            Logger.getLogger(Registration.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        try{
            int num = Integer.parseInt(txt_age.getText());
            // is an integer!
            if(txt_first.getText() == null || txt_last.getText() == null || "".equals(txt_age.getText()) || txt_occupation.getText() == null || txt_gender.getText() == null || txt_email.getText() == null || txt_nim.getText() == null || String.valueOf(txt_password.getPassword()) == null || String.valueOf(txt_cpassword.getPassword()) == null )
            {
                themessage.setText("Kindly fill all fields!!!");
                themessage.setBackground(Color.RED);
                timer1.start();
            }else if(String.valueOf(txt_password.getPassword()) == null ? String.valueOf(txt_cpassword.getPassword()) != null : !String.valueOf(txt_password.getPassword()).equals(String.valueOf(txt_cpassword.getPassword()))){
                themessage.setText("Confirm Password does not match password!!!");
                themessage.setBackground(Color.RED);
                timer1.start();
            }else if(Integer.parseInt(txt_age.getText()) < 18){
                themessage.setText("When you are 18 years old you would be able to vote!!!");
                themessage.setBackground(Color.RED);
                timer1.start();
            }else{
                // TODO add your handling code here:
                Connection conn;
                PreparedStatement reg,vn;
                String vinnumber = null;
                try {            
                    try {
                        Class.forName("com.mysql.jdbc.Driver");
                        System.out.println("Driver loaded!");
                    } catch (ClassNotFoundException e) {
                        throw new IllegalStateException("Cannot find the driver in the classpath!", e);
                    }
                    conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/bordacount", "root", "IBUKUN");
                    reg = conn.prepareStatement("INSERT INTO users (vin, password, user_first, user_last, user_age, user_occup, user_gender, user_mail, user_nim) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)");
                    reg.setString(1, vin);
                    reg.setString(2, String.valueOf(txt_password.getPassword()));
                    reg.setString(3, txt_first.getText());
                    reg.setString(4, txt_last.getText());
                    reg.setString(5, txt_age.getText());
                    reg.setString(6, txt_occupation.getText());
                    reg.setString(7, txt_gender.getText());
                    reg.setString(8, txt_email.getText());
                    reg.setString(9, txt_nim.getText());

                    reg.execute();
                    txt_first.setText("");
                    txt_last.setText("");
                    txt_age.setText("");
                    txt_occupation.setText("");
                    txt_gender.setText("");
                    txt_email.setText("");
                    txt_nim.setText("");
                    txt_password.setText("");
                    txt_cpassword.setText("");

                    vn = conn.prepareStatement("SELECT * FROM `users` ORDER BY user_id DESC LIMIT 1");
                    ResultSet vnresult = vn.executeQuery();
                    if(vnresult.next()){
                        vinnumber = vnresult.getString("vin");
                    }
                    themessage.setText("Registration Successful, You can now Login \n Your VIN is "+vinnumber);
                    themessage.setBackground(Color.GREEN);
                    timer1.start();
                } catch (SQLException ex) {
                    Logger.getLogger(Registration.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
          } catch (NumberFormatException e) {
            // not an integer!
            themessage.setText("Your Age is not a number!!!");
            themessage.setBackground(Color.RED);
            timer1.start();
          }
    }//GEN-LAST:event_btn_registerActionPerformed

    private void okActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okActionPerformed
        // TODO add your handling code here:
        timer2.start();
    }//GEN-LAST:event_okActionPerformed

    private void loginnowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginnowActionPerformed
        // TODO add your handling code here:
        dispose();
        Login thelogin = new Login();
        thelogin.setVisible(true);
    }//GEN-LAST:event_loginnowActionPerformed

    private void txt_firstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_firstActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_firstActionPerformed

    /**
     * @param args the command line arguments
     */
                
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Registration().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_register;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbl_password;
    private javax.swing.JLabel lbl_password1;
    private javax.swing.JLabel lbl_username;
    private javax.swing.JLabel lbl_username1;
    private javax.swing.JLabel lbl_username2;
    private javax.swing.JLabel lbl_username3;
    private javax.swing.JLabel lbl_username4;
    private javax.swing.JLabel lbl_username6;
    private javax.swing.JLabel lbl_username7;
    private javax.swing.JButton loginnow;
    private javax.swing.JPanel messagebox;
    private javax.swing.JButton ok;
    private javax.swing.JLabel themessage;
    private javax.swing.JTextField txt_age;
    private javax.swing.JPasswordField txt_cpassword;
    private javax.swing.JTextField txt_email;
    private javax.swing.JTextField txt_first;
    private javax.swing.JTextField txt_gender;
    private javax.swing.JTextField txt_last;
    private javax.swing.JTextField txt_nim;
    private javax.swing.JTextField txt_occupation;
    private javax.swing.JPasswordField txt_password;
    // End of variables declaration//GEN-END:variables
}
